apiVersion: v1
kind: Task
metadata:
  name: task-1
spec:
  containers:
    - image: poorlydefinedbehaviour/kubia
      name: kubia-1
      ports:
        - containerPort: 8894
          protocol: TCP
